# -*- coding: utf-8 -*-
"""DecisionTreeAppleOrange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1piCfkxaovl_JLvlx4I16lOfhCXgXESZK
"""

from sklearn import tree

# Gathering training data
# Possible string set features
# features = [[155, “rough”], [180, “rough”], [135, “smooth”], [110, “smooth”]] 

# Input to classifier- 2 param, boolean
features = [[155, 0], [180, 0], [135, 1], [110, 1]] # scikit-learn requires real-valued features

# labels = (1=orange) (0=apple)
labels = [1, 1, 0, 0]

# Training classifier
classifier = tree.DecisionTreeClassifier() # using decision tree classifier
classifier = classifier.fit(features, labels) # Find patterns in data

# Making predictions based off hardocded input
print (classifier.predict([[120, 1]]))
print (classifier.predict([[170, 0]]))